name: Healthz Ping

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping healthz endpoint
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.HEALTHZ_URL }}/v1/healthz)
          echo "Health check response: $response"

          if [ "$response" -eq 200 ]; then
            echo "Health check passed"
            exit 0
          else
            echo "Health check failed with status code: $response"
            exit 1
          fi

      - name: Report failure
        if: failure()
        run: echo "Health check failed."
